name: Ubuntu

on: [push]

jobs:
  build-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: install-openexr-v2.3.0
      run: |
        curl -L https://github.com/AcademySoftwareFoundation/Imath/archive/refs/tags/v3.0.2.tar.gz | tar -xvz
        mkdir build-imath
        cd build-imath
        cmake ../Imath-3.0.2 -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF
        make
        sudo make install
    - name: install-other-build-dependencies
      run: sudo apt-get -y install libeigen3-dev libglu1-mesa-dev xorg-dev
    - name: submodule
      run: git submodule update --init --recursive
    - name: cmake
      run: |
        cmake . -DELASTY_EXAMPLES=ON -DELASTY_TESTS=ON
    - name: make
      run: make
    - name: ctest
      run: ctest --verbose
